service: pedirPizzas

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  environment:
    REGION: ${self:provider.region}
    PENDING_ORDER_QUEUE:
      Ref: PendingOrdersQueue

functions:
  hacerPedido:
    handler: handler.hacerPedido
    events:
      - http:
          method: post
          path: pedido

resources:
  Resources:
    PendingOrdersQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "PendingOrdersQueue"
